name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Java Kurulumu (JDK 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Kütüphaneleri Yükle
        run: npm install

      - name: Gradle İzinlerini Ver
        run: chmod +x android/gradlew

      # --- İŞTE SİHİRLİ DOKUNUŞ BURASI ---
      # Sistem ne derse desin, local.properties dosyası son sözü söyler.
      - name: Create local.properties (Force NDK Path)
        run: |
          echo "ndk.dir=/usr/local/lib/android/sdk/ndk/26.1.10909125" > android/local.properties
          echo "sdk.dir=/usr/local/lib/android/sdk" >> android/local.properties
          cat android/local.properties
      # -----------------------------------

      - name: APK Oluştur (Release)
        working-directory: android
        run: ./gradlew assembleRelease --no-daemon

      - name: APK'yı Yükle (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/**/*.apk