name: Android Build

on:
  push:
    branches: [ main ]

env:
  ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.1.10909125

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Java Kurulumu (JDK 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Kütüphaneleri Yükle
        run: npm install

      - name: Gradle İzinlerini Ver
        run: chmod +x android/gradlew

      # --- BUKALEMUN TAKTİĞİ BURADA ---
      - name: NDK 26'yı NDK 27 Gibi Göster (Hile)
        run: |
          echo "NDK 27 klasörü temizleniyor..."
          sudo rm -rf /usr/local/lib/android/sdk/ndk/27.0.12077973
          
          echo "NDK 26, NDK 27 kılığına giriyor..."
          # NDK 26 klasörüne '27.0.12077973' adıyla sembolik link veriyoruz
          sudo ln -s /usr/local/lib/android/sdk/ndk/26.1.10909125 /usr/local/lib/android/sdk/ndk/27.0.12077973
          
          echo "İşlem Tamam! Sistem artık NDK 27 var sanıyor ama 26 kullanacak."
      # -------------------------------

      - name: APK Oluştur (Release)
        working-directory: android
        # Buradaki -Pandroid.ndkVersion kısmını kaldırdık çünkü artık kandırmaca yapıyoruz
        run: ./gradlew assembleRelease --no-daemon

      - name: APK'yı Yükle (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/**/*.apk